apiVersion: v1
kind: Service
metadata:
  name: newk8f
spec:
  selector:
    app: k8fa
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8fa
spec:
  selector:
    matchLabels:
      app: k8fa
  replicas: 5
  template:
    metadata:
      labels:
        app: k8fa
    spec:
      containers:
        - name: k8fa
          image: k8f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
