name: doctl

on:
  push:
    branches: [ master ]
    paths:
      - 'config/**'
      - 'site/**'
      - 'Dockerfile'
      - '.github/workflows/**'

env:
  IMAGE_NAME: frontend

jobs:
  build:
    
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Get current date time    
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%H%M')"
    
    - name: Checkout master
      uses: actions/checkout@master

    - name: Test with environment variables
      run: docker build -t $RELEASE_NAME .
      env:
        RELEASE_NAME: frontend-${{ steps.date.outputs.date }}

    
