name: doctl

on:
  push:
    branches: [ master ]
    paths:
      - 'config/**'
      - 'site/**'
      - 'Dockerfile'
      - '.github/workflows/**'

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: frontend-`date +\%Y-\%m-\%d--\%H\%M`

jobs:
  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    # - name: Update SHA
    #   run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/site/_meta

    - name: Build image
      run: docker build -t $IMAGE_NAME .
