name: doctl

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/**'

env:
  IMAGE_NAME: frontend

jobs:
  build:
    
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Get current date time    
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d--%H%M')"
    
    - name: Checkout master
      uses: actions/checkout@master

    - name: Build image
      run: docker build -t ghcr.io/shrestharajat/frontend-${{ steps.date.outputs.date }} .
    
    - name: Log into registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Push to GHCR
      run: docker push ghcr.io/shrestharajat/frontend-${{ steps.date.outputs.date }}

